name: my_portfolio
description: flutter_web_portfolio.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  animations: ^2.0.0
  container_tab_indicator: ^0.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.0.0
  google_fonts: ^6.2.1
  lottie: ^2.2.0
  percent_indicator: ^3.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.0.4

flutter_native_splash:
  color: "#888e93"
  image: assets/images/splash.png
  web_image_mode: center

dev_dependencies:
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/imgs/
